#!/bin/bash
apt-get -y remove vino
apt-get -y install x11vnc
mkdir /etc/x11vnc
#setup password:
x11vnc -storepasswd 123456 /etc/x11vnc.pass
nano /lib/systemd/system/x11vnc.service
# PUT THIS TO /lib/systemd/system/x11vnc.service-----------
[Unit]
Description=Start x11vnc at startup.
Requires=display-manager.service
After=display-manager.service

[Service]
ExecStart=/usr/bin/x11vnc -xkb -noxrecord -noxfixes -noxdamage -display :0 -auth guess -rfbauth /etc/x11vnc.pass
ExecStop=/usr/bin/killall x11vnc
Restart=on-failure
Restart-sec=2

[Install]
WantedBy=multi-user.target
#----------------------------------------------------------
systemctl daemon-reload
systemctl enable x11vnc.service
systemctl start x11vnc.service
systemctl status x11vnc.service
x11vnc -rfbauth /etc/x11vnc.passwd
